Create Populate cache workflow

diff --git a/.github/actions/setup-env/action.yml b/.github/actions/setup-env/action.yml
--- a/.github/actions/setup-env/action.yml
+++ b/.github/actions/setup-env/action.yml
@@ -13,7 +13,7 @@ inputs:
   cache-restore:
     description: Whether to restore the pnpm cache
     required: false
-    default: "false"
+    default: "true"
   cache-save:
     description: Whether to save the pnpm cache
     required: false
@@ -26,15 +26,25 @@ inputs:
     description: Path to the package.json file
     required: false
     default: "package.json"
+outputs:
+  cache-hit:
+    description: Whether the cache was restored
+    value: ${{ steps.node.outputs.cache-hit }}
 
 runs:
   using: composite
   steps:
+    - if: inputs.cache-save == 'true' && inputs.cache-restore == 'false'
+      run: |
+        echo "::error::Saving the cache without restoring it is not supported"
+        exit 1
+      shell: bash
     - uses: pnpm/action-setup@v4
       with:
         version: ${{ inputs.pnpm-version }}
         package_json_file: ${{ inputs.package-json }}
     - uses: actions/setup-node@v4
+      id: node
       with:
         node-version: ${{ inputs.node-version }}
         cache: ${{ inputs.cache-save == 'true' && 'pnpm' || '' }}
